name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Publish tt_submission artifact
        uses: actions/upload-artifact@v4
        with:
          name: tt_submission
          path: |
            src/*
            docs/*
            tt_submission/*
            info.yaml
            LICENSE

      - name: Upload gds_render (png) artifact
        uses: actions/upload-artifact@v4
        with:
          name: gds_render
          path: 'gds_render.png'

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttgf26a

  gl_test:
    needs: gds
    strategy:
      matrix:
        target:
          - core
          - prog
          - peri_num_2
          - peri_num_3
          - peri_num_5
          - peri_num_8
          - peri_num_10
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: MichaelBell/tt-gds-action/gl_test@ttgf0p3
        with:
          make-targets: ${{ matrix.target }}

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttgf26a
